apiVersion: v1
kind: Namespace
metadata:
  name: provider-docker-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-docker
  namespace: provider-docker-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-docker
  template:
    metadata:
      labels:
        app: provider-docker
    spec:
      containers:
      - name: provider
        image: ghcr.io/rossigee/provider-docker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: GOMAXPROCS
          value: "1"
        - name: GOMEMLIMIT
          value: "512MiB"
        args:
        - --debug
        - --poll=1m
        - --max-reconcile-rate=10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      serviceAccountName: provider-docker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-docker
  namespace: provider-docker-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-docker
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "container.docker.crossplane.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "compose.docker.crossplane.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "docker.crossplane.io"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-docker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-docker
subjects:
- kind: ServiceAccount
  name: provider-docker
  namespace: provider-docker-system